### PR TITLE
Added tests

### PR DESCRIPTION
**Pull request by karlbright**
I've split up the "levels" in the original demo and tested them individually. This makes for some interesting tests, especially at level 2(Two).

The test descriptions could do with some work but i've tried to make them as short as possible while making it clear what's happening.

### CODE REVIEW

**Comment by karlbright** [comment]
It should be noted that these tests could do with some cleanup in terms of how they are organised, but it shows how the process works through the tests. Also the use of textContent and indexOf isn't great, and obviously quite fragile, but i think it's ok for this?

**Comment by karlbright** [comment]
Cut down test time from 4.5s~ to 1s~. We don't need to worry about the beforeEach rendering here.

**Comment by JedWatson** [comment]
Awesome work @karlbright 

There's a catch here (and I should make it much clearer in the Readme) - the component source is actually in `src` and that gets built to `lib` by Babel with the `npm start` / `npm run build` etc. scripts.

So you've refactored the lib folder but it'll get blown away as soon as anyone else works with it.

Can you port your changes (including the tests) into `src`?

**Comment by karlbright** [comment]
@JedWatson Ah, my bad. I probably should have had a better look at that as I tend to put my own files in src. No problem, should be easy :)

**Comment by karlbright** [comment]
Sorted. I just used babel-jest as you're already using babel-core within react-component-gulp-tasks.

**Comment by JedWatson** [comment]
Nice - that was fast!

qq: why point the entry file at `index.js`? should be `lib/ContextExample.js` (was pointed at src for some reason, but index.js doesn't exist)

**Comment by karlbright** [comment]
Think that's just a stuff up, didn't catch it as was never building. Can
fix that up though.

**Comment by JedWatson** [comment]
No worries - just wanted to check we hadn't missed anything!

**Comment by JedWatson** [comment]
Getting errors (of the wrong kind) when I run this - am I missing something?

screen shot 2015-05-29 at 11 54 13 am

**Comment by karlbright** [comment]
Whoa. Seg vault? That doesn't seem right. No idea, would need to have a
better look at it. That looks like a bigger issue than the written tests.

**Pull request merged**
